In [2]:
import numpy as np
import pandas as pd
import random

In [3]:
np.array([x for x in range(1,10) if x%2==0]) # create an array using list comprehension

array([2, 4, 6, 8])

In [4]:
a = np.array([[1,2,3], [4,5,6]])

In [5]:
for i in a:
    print(i)

[1 2 3]
[4 5 6]


In [6]:
for i in a.flat:
    print(i)

1
2
3
4
5
6


In [7]:
%timeit -n30 -r15 array1 = np.random.randint(1,100, 60_000) # controlling parameters of %timeit

2.32 ms ± 267 µs per loop (mean ± std. dev. of 15 runs, 30 loops each)


In [8]:
array1 = np.random.randint(1,100, 600)

array1.shape

(600,)

In [9]:
np.arange(11).sum()

55

In [10]:
a = np.arange(1, 200)
b = np.resize(a, (5,7))

print(b)
print("*****************")
print(b[0,2]) # print a specific element
print("*****************")
print(b[[0,2]]) # print only specific rows
print("*****************")
print(b[: , [2,3]]) # print specific columns

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]
 [22 23 24 25 26 27 28]
 [29 30 31 32 33 34 35]]
*****************
3
*****************
[[ 1  2  3  4  5  6  7]
 [15 16 17 18 19 20 21]]
*****************
[[ 3  4]
 [10 11]
 [17 18]
 [24 25]
 [31 32]]


In [11]:
# flatten performs deep copy; ravel performs shallow copy

In [12]:
pd.Series(99, range(5))

0    99
1    99
2    99
3    99
4    99
dtype: int64

In [14]:
pd.Series(88,range(1,5))

1    88
2    88
3    88
4    88
dtype: int64

In [15]:
pd.Series(77, range(1,6,2))

1    77
3    77
5    77
dtype: int64

In [32]:
scores = pd.DataFrame({'nikhil':[90,80,70], 'ankit': [99, 98, 97], 'mummy':[100, 99, 90]})

scores

nikhil  ankit  mummy
0      90     99    100
1      80     98     99
2      70     97     90

In [37]:
scores.index=['Test1', 'Test2', 'Test3']

scores

nikhil  ankit  mummy
Test1      90     99    100
Test2      80     98     99
Test3      70     97     90

In [21]:
scores.at['Test2', 'ankit']

98

In [22]:
scores.iat[1,2]

99

In [23]:
scores.sort_index(ascending=False)

nikhil  ankit  mummy
Test3      70     97     90
Test2      80     98     99
Test1      90     99    100

In [24]:
scores.sort_index(axis=1)

ankit  mummy  nikhil
Test1     99    100      90
Test2     98     99      80
Test3     97     90      70

In [25]:
scores.sort_values(by='Test1', axis=1)

nikhil  ankit  mummy
Test1      90     99    100
Test2      80     98     99
Test3      70     97     90

In [27]:
scores.loc['Test1'].sort_values()

nikhil     90
ankit      99
mummy     100
Name: Test1, dtype: int64

In [26]:
scores.T.sort_values(by='Test1')

Test1  Test2  Test3
nikhil     90     80     70
ankit      99     98     97
mummy     100     99     90

In [36]:
scores

nikhil  ankit  mummy
0      90     99    100
1      80     98     99
2      70     97     90

In [40]:
scores.sort_values(by='Test1', axis=1, ascending = False, inplace=True) # inplace does not create a copy, modifies the DF

scores

mummy  ankit  nikhil
Test1    100     99      90
Test2     99     98      80
Test3     90     97      70

In [45]:
scores.loc[['Test3'], ['mummy']]

mummy
Test3     90

In [46]:
scores.loc['Test3', 'mummy']

90